version: "3.8"
services:
  web:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./api/src:/code/src
      - ./api/server.py:/code/server.py
    restart: on-failure
