version: "3.8"

services:
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test-postgres-flask
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test-postgres-flask
  web:
    build: ./api
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - api/.env.dev
    depends_on:
      - db


volumes:
  postgres_data:
